version: "3"
services:
  plex:
    image: "linuxserver/plex"
    restart: "unless-stopped"
    network_mode: "host"
    environment:
        PUID: 1000
        PGID: 1001
        VERSION: "docker"
    volumes:
      - "/storage/media:/data:ro"
      - "/storage/transcode:/transcode"
      - "/home/abrar/docker/plex/config:/config"
      
  haproxy:
    image: 'haproxy:alpine'
    restart: "unless-stopped"
    depends_on:
      - transmission
    volumes:
      - "/home/abrar/myubuntu/docker/att/configs:/usr/local/etc/haproxy:ro"
      - "/var/lib/haproxy/dev/log:/dev/log"
    ports:
      - "9091:9091/tcp"
    
  transmission:
    image: "haugene/transmission-openvpn"
    restart: "unless-stopped"
    volumes:
      - "/storage/media:/media"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - "transmission.env"
    cap_add:
      - NET_ADMIN
  
  handbrake:
    image: "jlesage/handbrake"
    restart: "unless-stopped"
    environment:
      USER_ID: 1000
      GROUP_ID: 1001
      TZ: "America/Los_Angeles"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/home/abrar/docker/handbrake:/config:rw"
      - "/storage/media:/storage:ro"
      - "/storage/transcode/handbrake:/output:rw"
    ports:
      - "5800:5800/tcp"